### ISSUE TITLE
Install plugin

### ISSUE THREAD

**Issue by rafasegat** [floatinghotpot/cordova-plugin-mopub#16]
Hi

Im trying to install the plugin but occur this error

MacBook-Pro-de-Rafael:supercarros-app rafsegat$ cordova plugin add com.rjfun.cordova.mopub
Fetching plugin "com.rjfun.cordova.mopub" via npm
WARNING: com.rjfun.cordova.mopub has been renamed to cordova-plugin-mopub. You may not be getting the latest version! We suggest you `cordova plugin rm com.rjfun.cordova.mopub` and `cordova plugin add cordova-plugin-mopub`.
Fetching plugin "com.rjfun.cordova.mopub" via cordova plugins registry
Installing "com.rjfun.cordova.mopub" for android
Fetching plugin "com.rjfun.cordova.extension" via npm
WARNING: com.rjfun.cordova.extension has been renamed to cordova-plugin-extension. You may not be getting the latest version! We suggest you `cordova plugin rm com.rjfun.cordova.extension` and `cordova plugin add cordova-plugin-extension`.
Fetching plugin "com.rjfun.cordova.extension" via cordova plugins registry
Installing "com.rjfun.cordova.extension" for android
Fetching plugin "android.support.v4" via npm
WARNING: android.support.v4 has been renamed to cordova-plugin-android-support-v4. You may not be getting the latest version! We suggest you `cordova plugin rm android.support.v4` and `cordova plugin add cordova-plugin-android-support-v4`.
Fetching plugin "android.support.v4" via cordova plugins registry
Installing "android.support.v4" for android
Fetching plugin "https://github.com/floatinghotpot/google-play-services" via git clone
Repository "https://github.com/floatinghotpot/google-play-services" checked out to git ref "r19".
Failed to install 'com.rjfun.cordova.mopub':Error: Expected plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
Error: Expected plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:177:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:161:9
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by rafasegat** [comment]
The problem is 

Failed to install 'com.rjfun.cordova.mopub':Error: Expected plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices".

**Comment by floatinghotpot** [comment]
Please notice the message in your log: we suggest you ```cordova plugin rm com.rjfun.cordova.mopub``` and ```cordova plugin add cordova-plugin-mopub```.

As the id ```com.rjfun.cordova.mopub``` is old id in cordova plugin registry, and now is renamed to ```cordova-plugin-mopub``` after migrated to npm repository.

**Comment by rafasegat** [comment]
Thanks!! It installed very well.

But when i tried to run didnt work.
So I desinstalled the plugin and runned very wel..

Do you knwo whats happen?

Follow the error below.

--------------------------------------------------------------------


Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:preDexDebug
:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/rafsegat/Library/Android/sdk/build-tools/23.0.2/dx --dex --no-optimize --output /Projects/supercarros-app/platforms/android/build/intermediates/dex/debug --input-list=/Projects/supercarros-app/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 53.97 secs

/Projects/supercarros-app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Projects/supercarros-app/platforms/android/gradlew with args: cdvBuildDebug,-b,/Projects/supercarros-app/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /Projects/supercarros-app/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project
MacBook-Pro-de-Rafael:supercarros-app rafsegat$

**Comment by rafasegat** [comment]
Oh I got it.

Just desintalled a olf version Google V4 and worked fine.

Thanks and great plugin
