### ISSUE TITLE
starting showing BAD URL before few days ago its working fine

### ISSUE THREAD

**Issue by sanjaymobpair** [floatinghotpot/cordova-plugin-mopub#29]
before few days ago plugin working fine but now its showing error and Error CODE : 21, unspecified error
Error Log : 
07-12 12:18:03.712 11808-11808/com.mp.ballpool E/MoPub: Make sure to call MoPub#initializeSdk before loading an ad.
07-12 12:18:03.726 11808-11808/com.mp.ballpool I/WebViewFactory: Loading com.android.chrome version 67.0.3396.87 (code 339608712)
07-12 12:18:03.836 11808-11808/com.mp.ballpool I/cr_LibraryLoader: Time to load native libraries: 8 ms (timestamps 3010-3018)
07-12 12:18:03.865 11808-11808/com.mp.ballpool I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
07-12 12:18:03.867 11808-11808/com.mp.ballpool I/cr_LibraryLoader: Expected native library version number "67.0.3396.87", actual native library version number "67.0.3396.87"
07-12 12:18:03.915 11808-11913/com.mp.ballpool W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
07-12 12:18:03.942 11808-11808/com.mp.ballpool I/cr_BrowserStartup: Initializing chromium process, singleProcess=false
07-12 12:18:03.943 11808-11808/com.mp.ballpool I/cr_base: Android Locale: en_US requires .pak files: [en-GB.pak, en-US.pak]
07-12 12:18:03.965 11808-11808/com.mp.ballpool W/ResourceType: Failure getting entry for 0x7f120466 (t=17 e=1126) (error -2147483647)
07-12 12:18:04.249 11808-11819/com.mp.ballpool I/zygote: Background concurrent copying GC freed 6746(860KB) AllocSpace objects, 14(344KB) LOS objects, 49% free, 1852KB/3MB, paused 495us total 108.950ms
07-12 12:18:04.253 11808-11944/com.mp.ballpool E/Volley: [2180] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 
    java.lang.RuntimeException: Bad URL 
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:590)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:92)
        at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:53)
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:131)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120) 
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:87) 

help me to solve this issue

**Comment by RhuanGonzaga** [comment]
I have the same problem, did you find any solution ? I think this plugin is not compatible with latest mopub sdk.

**Comment by Shchvova** [comment]
I had similar issue. It got resolved by calling [`MoPub.initializeSdk()`](https://developers.mopub.com/docs/android/initialization/) on java side

**Comment by AlessioLuciani** [comment]
I had the same problem, in my case, even though I called `MoPub.initializeSdk()`, I gave no time to the call to complete and tried to load an ad in the meantime. Everything worked just fine using the SDK initialization completion listener to load the ad.
